"""add current_price to forecasts_cache

Revision ID: 7a097fa04cb4
Revises: 727f5320ff3c
Create Date: 2026-09-05 12:59:14.284414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a097fa04cb4'
down_revision: Union[str, Sequence[str], None] = '727f5320ff3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts_cache', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts_cache', 'current_price')
    # ### end Alembic commands ###
